export class LabelConstant {
  static readonly CATCH_YOUR_POKEMON = 'LABEL.CATCH_YOUR_POKEMON';
  static readonly YOU_DONT_HAVE_COLLECTION_POKEMON =
    'LABEL.YOU_DONT_HAVE_COLLECTION_POKEMON';
  static readonly YOUR_POKEMON_COLLECTIONS = 'LABEL.YOUR_POKEMON_COLLECTIONS';
}
